version: '2'
services:
    employeemanagement-app:
        image: employeemanagement
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://employeemanagement-mysql:3306/employeemanagement?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    employeemanagement-mysql:
        extends:
            file: mysql.yml
            service: employeemanagement-mysql
